### ISSUE TITLE
Extraction Error in Alflytics with Alfresco v6: Rest call failed

### ISSUE THREAD

**Issue by abipriya95** [fcorti/Alflytics#24]
Hi,
    I am facing issue with extraction process of alflytics. It works fine with the Alfresco version 5.2. I tried running it with Alfresco 6 and I get below error. Does Alflytics work with Alfresco version 6?
    Here is the log

    Get Alfresco repository from Alfresco in tmp - Starting entry [Create targetPathForCategories]
2019/08/01 14:33:59 - Get Alfresco repository from Alfresco in tmp - Starting entry [Get REST in json for categories]
2019/08/01 14:33:59 - Get REST in json - Starting entry [Set hasMoreItems]
2019/08/01 14:33:59 - Get REST in json - Starting entry [Set targetFile]
2019/08/01 14:33:59 - Get REST in json - Starting entry [Get REST in json]
2019/08/01 14:33:59 - Get REST in json - Loading transformation from repository [Get REST in json] in directory [/public/Alflytics/ETL/Staging/Util]
2019/08/01 14:33:59 - Get REST in json - Using legacy execution engine
2019/08/01 14:33:59 - Get REST in json - Dispatching started for transformation [Get REST in json]
2019/08/01 14:34:00 - Data Grid.0 - Finished processing (I=0, O=0, R=0, W=1, U=0, E=0)
2019/08/01 14:34:00 - Variables replace.0 - Finished processing (I=0, O=0, R=1, W=1, U=0, E=0)
2019/08/01 14:34:00 - Select values.0 - Finished processing (I=0, O=0, R=1, W=1, U=0, E=0)
2019/08/01 14:34:00 - Abort.0 - ERROR (version 7.1.0.0-12, build 1 from 2017-05-16 17.18.02 by buildguy) : Row nr 1 causing abort : [{"query":{"query":"(TYPE:\"cm:category\")","language": "afts"},"sort":[{"type":"FIELD","field":"cm:modified","ascending": true},{"type":"FIELD","field":"sys:dbid","ascending":true}],"include":["properties"],"paging":{"maxItems": 5000,"skipCount":0}}], [http://localhost:8081/alfresco/api/-default-/public/search/versions/1/search], [POST], [{"error":{"errorKey":"framework.exception.ApiDefault","statusCode":500,"briefSummary":"07010026 ","stackTrace":"For security reasons the stack trace is no longer displayed, but the property is kept for previous versions","descriptionURL":"https://api-explorer.alfresco.com","logId":"97b9016f-6f9a-4047-bc97-402f806edc49"}}], [500]
2019/08/01 14:34:00 - Abort.0 - ERROR (version 7.1.0.0-12, build 1 from 2017-05-16 17.18.02 by buildguy) : Rest call failed.
2019/08/01 14:34:00 - Abort.0 - Finished processing (I=0, O=0, R=1, W=1, U=0, E=1)
2019/08/01 14:34:00 - Get REST in json - Transformation detected one or more steps with errors.
2019/08/01 14:34:00 - Get REST in json - Transformation is killing the other steps!
2019/08/01 14:34:00 - Set Variables.0 - We didn't receive a row while setting the default values.
2019/08/01 14:34:00 - Set Variables.0 - Finished after 0 rows.
2019/08/01 14:34:00 - Switch / Case.0 - Finished processing (I=0, O=0, R=1, W=1, U=0, E=0)
2019/08/01 14:34:00 - Get REST in json - ERROR (version 7.1.0.0-12, build 1 from 2017-05-16 17.18.02 by buildguy) : Errors detected!
2019/08/01 14:34:00 - REST Client.0 - Finished processing (I=0, O=0, R=1, W=1, U=0, E=0)
2019/08/01 14:34:00 - Get REST in json - ERROR (version 7.1.0.0-12, build 1 from 2017-05-16 17.18.02 by buildguy) : Errors detected!
2019/08/01 14:34:00 - Get REST in json - Finished job entry [Get REST in json] (result=[false])
2019/08/01 14:34:00 - Get REST in json - Finished job entry [Set targetFile] (result=[false])
2019/08/01 14:34:00 - Get REST in json - Finished job entry [Set hasMoreItems] (result=[false])

**Comment by fcorti** [comment]
Hi,

The error is calling the following query endpoint on Alfresco.
http://localhost:8081/alfresco/api/-default-/public/search/versions/1/search
With parameter:
{"query":{"query":"(TYPE:"cm:category")","language": "afts"},"sort":[{"type":"FIELD","field":"cm:modified","ascending": true},{"type":"FIELD","field":"sys:dbid","ascending":true}

You can check on Alfresco side if correct or not.

I'm looking for collaborations and contributions on testing Alflytics on Alfresco 6.
Let me know if you might be interested, writing to me in private.

**Comment by abipriya95** [comment]
Hi,
    Thanks for the response. Sure... we are using Alfresco 6 right now. We needed Alflytics to work with Alfresco v6 also.

**Comment by Dnhatsave** [comment]
Hi,

I've the same problem on Alfresco 6.1.2 i got this error 

rt.0 - ERROR (version 7.1.0.0-12, build 1 from 2017-05-16 17.18.02 by buildguy) : Row nr 1 causing abort : [{"query":{"query": "(((TYPE:\"cm:content\") OR (TYPE:\"cm:folder\")) AND NOT (TYPE:\"cm:systemfolder\") AND (@cm:modified:[\"2001-01-01T00:00:00.000Z\" TO MAX]))","language":"afts"},"paging":{"maxItems":1,"skipCount":1000000000}}], [http://172.31.4.121:8080/alfresco/api/-default-/public/search/versions/1/search], [POST], [{"error":{"errorKey":"framework.exception.ApiDefault","statusCode":500,"briefSummary":"05231071 ","stackTrace":"For security reasons the stack trace is no longer displayed, but the property is kept for previous versions","descriptionURL":"https://api-explorer.alfresco.com","logId":"dfe0452b-91c4-4ead-b09b-c8e730cb0f5e"}}], [500]
2020/06/23 11:03:15 - Abort.0 - ERROR (version 7.1.0.0-12, build 1 from 2017-05-16 17.18.02 by buildguy) : Rest call failed.

On alfresco side i got this


ERROR [api.search.SearchApiWebscript] [http-nio-8080-exec-8] dfe0452b-91c4-4ead-b09b-c8e730cb0f5e : [org.alfresco.repo.search.impl.solr.SolrQueryHTTPClient.executeQuery(SolrQueryHTTPClient.java:598), org.alfresco.repo.search.impl.solr.SolrQueryLanguage.executeQuery(SolrQueryLanguage.java:52), org.alfresco.repo.search.impl.solr.DbOrIndexSwitchingQueryLanguage.executeQuery(DbOrIndexSwitchingQueryLanguage.java:217), org.alfresco.repo.search.impl.solr.SolrSearchService.query(SolrSearchService.java:354), org.alfresco.repo.search.SearcherComponent.query(SearcherComponent.java:84), sun.reflect.GeneratedMethodAccessor1194.invoke(Unknown Source), sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43), java.lang.reflect.Method.invoke(Method.java:498), org.alfresco.repo.management.subsystems.SubsystemProxyFactory$1.invoke(SubsystemProxyFactory.java:79), org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186), org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212), com.sun.proxy.$Proxy31.query(Unknown Source), org.alfresco.repo.search.impl.SearchServiceSubSystemDelegator.query(SearchServiceSubSystemDelegator.java:133), sun.reflect.GeneratedMethodAccessor1194.invoke(Unknown Source), sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43), java.lang.reflect.Method.invoke(Method.java:498), org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:343), org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:198), org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163), net.sf.acegisecurity.intercept.method.aopalliance.MethodSecurityInterceptor.invoke(MethodSecurityInterceptor.java:80), org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186), org.alfresco.repo.security.permissions.impl.ExceptionTranslatorMethodInterceptor.invoke(ExceptionTranslatorMethodInterceptor.java:53), org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186), org.alfresco.repo.audit.AuditMethodInterceptor.invoke(AuditMethodInterceptor.java:166), org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186), org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:294), org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:98), org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186), org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212), com.sun.proxy.$Proxy31.query(Unknown Source), org.alfresco.rest.api.search.SearchApiWebscript.execute(SearchApiWebscript.java:100), org.alfresco.repo.web.scripts.RepositoryContainer$3.execute(RepositoryContainer.java:519), org.alfresco.repo.transaction.RetryingTransactionHelper.doInTransaction(RetryingTransactionHelper.java:450), org.alfresco.repo.web.scripts.RepositoryContainer.transactionedExecute(RepositoryContainer.java:587), org.alfresco.repo.web.scripts.RepositoryContainer.transactionedExecuteAs(RepositoryContainer.java:656), org.alfresco.repo.web.scripts.RepositoryContainer.executeScriptInternal(RepositoryContainer.java:428), org.alfresco.repo.web.scripts.RepositoryContainer.executeScript(RepositoryContainer.java:308), org.alfresco.rest.api.PublicApiRepositoryContainer.access$001(PublicApiRepositoryContainer.java:47), org.alfresco.rest.api.PublicApiRepositoryContainer$1.doWork(PublicApiRepositoryContainer.java:84), org.alfresco.repo.tenant.TenantUtil.runAsWork(TenantUtil.java:126), org.alfresco.repo.tenant.TenantUtil.runAsTenant(TenantUtil.java:95), org.alfresco.rest.api.PublicApiRepositoryContainer.executeScript(PublicApiRepositoryContainer.java:80), org.springframework.extensions.webscripts.AbstractRuntime.executeScript(AbstractRuntime.java:399), org.springframework.extensions.webscripts.AbstractRuntime.executeScript(AbstractRuntime.java:210), org.alfresco.repo.web.scripts.TenantWebScriptServlet.service(TenantWebScriptServlet.java:82), javax.servlet.http.HttpServlet.service(HttpServlet.java:729), org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:292), org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207), org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52), org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240), org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207), org.alfresco.module.aosmodule.service.ContextRootFilter.doFilter(ContextRootFilter.java:93), org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240), org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207), org.alfresco.repo.web.filter.beans.NullFilter.doFilter(NullFilter.java:75), sun.reflect.GeneratedMethodAccessor527.invoke(Unknown Source), sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43), java.lang.reflect.Method.invoke(Method.java:498), org.alfresco.repo.management.subsystems.ChainingSubsystemProxyFactory$1.invoke(ChainingSubsystemProxyFactory.java:132), org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186), org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212), com.sun.proxy.$Proxy162.doFilter(Unknown Source), org.alfresco.repo.web.filter.beans.BeanProxyFilter.doFilter(BeanProxyFilter.java:89), org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240), org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207), org.alfresco.web.app.servlet.GlobalLocalizationFilter.doFilter(GlobalLocalizationFilter.java:68), org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240), org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207), org.alfresco.web.app.servlet.ClearSecurityContextFilter.doFilter(ClearSecurityContextFilter.java:53), org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240), org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207), org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:212), org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:94), org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:504), org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:141), org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79), org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:620), org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88), org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:502), org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1132), org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:684), org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1539), org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1495), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624), org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61), java.lang.Thread.run(Thread.java:748)]




After that solr go down, is there any fix for this problem ?

**Comment by fcorti** [comment]
Hi Dercio,

The error on Pentaho side says that the REST call failed... and this is true, considering that on the Alfresco side the query failed.

The problem seems to be on Alfresco/Solr side.

Mi suggestions to raise the same query using a REST endpoint directly on Alfresco an solve the problem there.

I hope this helps you.

**Comment by Dnhatsave** [comment]
Thanks for the response Francesco,

I've follow you recommendation and i change the query on PDI directly for alfresco and now i got this error

ERROR (version 7.1.0.0-12, build 1 from 2017-05-16 17.18.02 by buildguy) : Row nr 1 causing abort : [{"query":{"query": "(((TYPE:\"cm:content\") OR (TYPE:\"cm:folder\")) AND NOT (TYPE:\"cm:systemfolder\") AND (@cm:modified:[\"2001-01-01T00:00:00.000Z\" TO MAX]))","language":"afts"},"paging":{"maxItems":1,"skipCount":1000000000}}], [http://172.31.4.121:8080/alfresco/api/-default-/public/search/versions/1/search], [POST], [{"error":{"errorKey":"framework.exception.ApiDefault","statusCode":500,"briefSummary":"053017816 ","stackTrace":"For security reasons the stack trace is no longer displayed, but the property is kept for previous versions","descriptionURL":"https://api-explorer.alfresco.com","logId":"74dae5b1-5a80-43b9-af24-7e4b7f268ef5"}}], [500]
2020/06/30 13:55:48 - Abort.0 - ERROR (version 7.1.0.0-12, build 1 from 2017-05-16 17.18.02 by buildguy) : Rest call failed. 
OR (version 7.1.0.0-12, build 1 from 2017-05-16 17.18.02 by buildguy) : Rest call failed.

2020/06/30 13:55:52 - Get REST in json - ERROR (version 7.1.0.0-12, build 1 from 2017-05-16 17.18.02 by buildguy) : Errors detected!
2020/06/30 13:55:52 - Get REST in json - ERROR (version 7.1.0.0-12, build 1 from 2017-05-16 17.18.02 by buildguy) : Errors detected!

it seems that somewhere at the query the url [http://172.31.4.121:8080/alfresco/api/-default-/public/search/versions/1/search
] (url) its used, i look that url its not longer supported at alfresco 6 this can be considered a bug of Alflytics  whit Alfresco 6 versions ??

**Comment by fcorti** [comment]
The REST endpoint should exist, as you can see from swagger.

https://api-explorer.alfresco.com/api-explorer/#!/search/search

Did you manage to try the direct REST API call to reproduce the error?

**Comment by Dnhatsave** [comment]
How can i call direct REST API ? 

I've only execute the url  /alfresco/api/-default-/public/search/versions/1/search form browser  and still shows the message

"stackTrace": "For security reasons the stack trace is no longer displayed, but the property is kept for previous versions",

    "descriptionURL": "https://api-explorer.alfresco.com"

**Comment by fcorti** [comment]
https://www.postman.com/

Is one of the best tool for this purpose.

**Comment by Dnhatsave** [comment]
I got the same message with postman as you can see 

![Screenshot 2020-07-02 at 14 01 23](https://user-images.githubusercontent.com/43370602/86356024-ddfba300-bc6b-11ea-8196-1bb17070c4bf.png)

**Comment by fcorti** [comment]
What the Alfresco catalina.out log file says about the error?

**Comment by Dnhatsave** [comment]
The logs says

```
2020-07-02 14:41:10,401  ERROR [extensions.webscripts.AbstractRuntime] [http-nio-8080-exec-660] Exception from executeScript: 06020065 {0} n?o foi encontrada
 org.alfresco.rest.framework.core.exceptions.NotFoundException: 06020065 {0} n?o foi encontrada
	at org.alfresco.rest.framework.core.ResourceLookupDictionary.locateRelationResource(ResourceLookupDictionary.java:95)
	at org.alfresco.rest.framework.core.ResourceLookupDictionary.locateEntityResource(ResourceLookupDictionary.java:57)
	at org.alfresco.rest.framework.core.ResourceLookupDictionary.locateResource(ResourceLookupDictionary.java:152)
	at org.alfresco.rest.api.PublicApiDeclarativeRegistry.getResourceWithMetadataOrNull(PublicApiDeclarativeRegistry.java:263)
	at org.alfresco.rest.api.PublicApiDeclarativeRegistry.findWebScript(PublicApiDeclarativeRegistry.java:124)
	at org.springframework.extensions.webscripts.AbstractRuntime.executeScript(AbstractRuntime.java:165)
	at org.alfresco.repo.web.scripts.TenantWebScriptServlet.service(TenantWebScriptServlet.java:82)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:292)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.alfresco.module.aosmodule.service.ContextRootFilter.doFilter(ContextRootFilter.java:93)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.alfresco.repo.web.filter.beans.NullFilter.doFilter(NullFilter.java:75)
	at sun.reflect.GeneratedMethodAccessor527.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.alfresco.repo.management.subsystems.ChainingSubsystemProxyFactory$1.invoke(ChainingSubsystemProxyFactory.java:132)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212)
	at com.sun.proxy.$Proxy162.doFilter(Unknown Source)
	at org.alfresco.repo.web.filter.beans.BeanProxyFilter.doFilter(BeanProxyFilter.java:89)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.alfresco.web.app.servlet.GlobalLocalizationFilter.doFilter(GlobalLocalizationFilter.java:68)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.alfresco.web.app.servlet.ClearSecurityContextFilter.doFilter(ClearSecurityContextFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:212)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:94)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:504)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:141)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:620)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:502)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1132)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:684)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1539)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1495)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by fcorti** [comment]
Sorry, I don't understand Spanish.
In every case, it seems there is a problem on the ACS side, not Pentaho (so Alflytics) side.
This is telling to me that you Alfresco installation has an issue (if confirmed).

**Comment by Dnhatsave** [comment]
its Portuguese,

translating the error says:

`For security reasons, stack tracking is no longer displayed, but ownership has been retained for previous versions`

**Comment by fcorti** [comment]
I was looking at the sceenshot.
It says: error 401 => Unauthorized
I think there is the wrong credentials in the postman call. 
;-)

**Comment by Dnhatsave** [comment]
Yes sure :-D, the credentials were wrong

I changed the header and had the error bellow

![Screenshot 2020-07-02 at 16 58 37](https://user-images.githubusercontent.com/43370602/86374269-a9481580-bc84-11ea-9102-1c1a3faf900d.png)

**Comment by fcorti** [comment]
Ok, now it is a 404.
Do you have a swagger client on Alfresco?
Can you retrieve the URI of the search endpoint?

**Comment by Dnhatsave** [comment]
it's my first time to hear the term swagger, but i think that i dont have it on Alfresco.
I don't have an URI for search at alfresco im using external Solr.

**Comment by fcorti** [comment]
You can ask in the hub.alfresco.com.
